---
excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://alejandrojuarezfitness.github.io
title: Alejandro Juarez - Fitness Professional
tagline: Supplementing the Active Mind
description: I'm a personal trainer in Austin, TX. I specialize in Strength Training, Conditioning, Weight Loss, CrossFit, and crafting personalized workout programs. <br /><br />I love to help people realize their goals and achieve their dreams. <br /><br />"Because you are alive, everything is possible."<br />&#8213; Thích Nh&#7845;t H&#7841;nh
paginate: 5
